services:
  - type: web
    name: personal-task-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn personal_task_management.wsgi
    autoDeploy: true
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: adminpassword
    postDeploy:
      - python manage.py migrate
      - python manage.py createsuperuser --noinput || true
